version: '3'

services:
  api:
    image: dockerized-mircoservices_api:latest
    container_name: dockerized-api
    restart: unless-stopped
    ports:
      - "80:8080"
      
  reverse:
    image: dockerized-mircoservices_reverse:latest
    container_name: dockerized-reverse
    restart: unless-stopped
    ports:
      - "8081:8081"