version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: dockerized-mircoservices_api:latest
    container_name: dockerized-api
    restart: unless-stopped
    ports:
      - "8080:8080"
      
  reverse:
    build:
      context: ./reverse
      dockerfile: Dockerfile
    image: dockerized-mircoservices_reverse:latest
    container_name: dockerized-reverse
    restart: unless-stopped
    ports:
      - "8081:8081"